name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.0.3
  - numpy<2 
  - libstdcxx-ng>=12 
  - libgcc-ng>=12 
  - pytest=7.4.4
  - scipy=1.13.1
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
